# Generated by Django 2.0.3 on 2018-06-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('visit1', models.CharField(blank=True, max_length=100)),
                ('visit2', models.CharField(blank=True, max_length=100)),
                ('visit3', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_worked', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('sub', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('lat_cordinate', models.FloatField(default=0)),
                ('long_cordinate', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='street',
            name='terr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Terr'),
        ),
        migrations.AddField(
            model_name='number',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Street'),
        ),
    ]
