# Generated by Django 2.0.3 on 2018-05-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='amount_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terr',
            name='lat_cordinate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terr',
            name='long_cordinate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terr',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
