# Generated by Django 2.0.3 on 2018-05-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180512_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terr',
            name='lat_cordinate',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terr',
            name='long_cordinate',
            field=models.BigIntegerField(default=0),
        ),
    ]
