# Generated by Django 2.1.4 on 2019-04-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190412_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='date_worked',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
