# Generated by Django 2.0.3 on 2018-05-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180512_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terr',
            name='lat_cordinate',
        ),
        migrations.RemoveField(
            model_name='terr',
            name='long_cordinate',
        ),
    ]
