# Generated by Django 2.0.3 on 2018-06-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180513_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('visit1', models.CharField(blank=True, max_length=100)),
                ('visit2', models.CharField(blank=True, max_length=100)),
                ('visit3', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='street',
            name='date_worked',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='number',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Street'),
        ),
    ]
