# Generated by Django 2.0.3 on 2018-06-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180610_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='terr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Terr'),
        ),
    ]
