# Generated by Django 2.0.3 on 2018-06-11 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_number_terr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='street',
        ),
        migrations.RemoveField(
            model_name='number',
            name='terr',
        ),
        migrations.RemoveField(
            model_name='street',
            name='amount_numbers',
        ),
        migrations.RemoveField(
            model_name='street',
            name='terr',
        ),
        migrations.AddField(
            model_name='street',
            name='numbers',
            field=models.ManyToManyField(through='main.Terr', to='main.Number'),
        ),
        migrations.AddField(
            model_name='terr',
            name='houses',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Number'),
        ),
        migrations.AddField(
            model_name='terr',
            name='street',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Street'),
        ),
    ]
