# Generated by Django 2.1.4 on 2019-04-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190430_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='last_updated',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
