# Generated by Django 2.1.4 on 2019-04-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190430_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number',
            options={},
        ),
    ]
