# Generated by Django 2.1.4 on 2019-04-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190430_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number',
            options={'ordering': ['value']},
        ),
    ]
