# Generated by Django 2.1.4 on 2019-05-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190430_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='last_updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
